package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"

	tea "charm.land/bubbletea/v2"

	"github.com/magik23/marchine/internal/config"
	"github.com/magik23/marchine/internal/mame"
	"github.com/magik23/marchine/internal/ui"
)

var version = "dev"

func main() {
	var (
		configPath = flag.String("config", "", "path to config.toml")
		demo       = flag.Bool("demo", false, "run with built-in demo entries")
		rescan     = flag.Bool("rescan", false, "force a fresh MAME index")
		initConfig = flag.Bool("init-config", false, "create a starter config if missing")
		showVer    = flag.Bool("version", false, "print version and exit")
		doctor     = flag.Bool("doctor", false, "print local MAME/config diagnostics and exit")
	)

	flag.Parse()

	if *showVer {
		fmt.Printf("marchine %s\n", version)
		return
	}

	path := *configPath
	if path == "" {
		var err error
		path, err = config.ConfigPath()
		if err != nil {
			fatal(err)
		}
	}

	if *initConfig {
		if err := ensureStarterConfig(path); err != nil {
			fatal(err)
		}
		fmt.Println(path)
		return
	}

	cfg, err := config.Load(path)
	if err != nil {
		fatal(err)
	}

	if *doctor {
		runDoctor(cfg, *rescan, path)
		return
	}

	model := ui.NewModel(cfg, path, *rescan, *demo)
	p := tea.NewProgram(model)

	if _, err := p.Run(); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "marchine:", err)
	os.Exit(1)
}

func ensureStarterConfig(path string) error {
	if _, err := os.Stat(path); err == nil {
		return nil
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	return os.WriteFile(path, []byte(starterConfig), 0o644)
}

const starterConfig = `# MARCHINE — Game Machinery.
# Generated by: marchine --init-config

theme = "violet"
startup_source = "arcade"

[arcade]
enabled = true
mame_command = "mame"
rom_paths = []
catver_path = ""
hide_clones = true
hide_preliminary = true

# Non-destructive UI preference:
# HIDE NON-ARCADE starts ON; the full index remains cached.
hide_junk = true

# Flat launch targets.
# Display name is independent from the real command.

# [[games]]
# name = "Terminator 2D"
# command = "steam"
# args = ["-applaunch", "1718460"]
`

func runDoctor(cfg config.Config, force bool, path string) {
	fmt.Println("MARCHINE // DOCTOR")
	fmt.Println("config:", path)
	fmt.Printf("custom games: %d\n", len(cfg.Games))

	if !cfg.Arcade.Enabled {
		fmt.Println("arcade: disabled")
		return
	}

	res, err := mame.Load(cfg.Arcade, force)
	if err != nil {
		fmt.Println("arcade error:", err)
		return
	}

	fmt.Println("mame:", res.MAMEVersion)

	if len(res.ROMPaths) == 0 {
		fmt.Println("rom paths: none detected")
	} else {
		for _, p := range res.ROMPaths {
			fmt.Println("rom path:", p)
		}
	}

	if res.CatVerUsed != "" {
		fmt.Println("catver:", res.CatVerUsed)
	} else {
		fmt.Println("catver: not found (optional)")
	}

	fmt.Printf("visible arcade games: %d\n", len(res.Games))

	if res.Warning != "" {
		fmt.Println("warning:", res.Warning)
	}
}
